### PR TITLE
Release notes of current and upcoming versions

### PR DESCRIPTION
**Pull request by mrnolte**

### CODE REVIEW

**Comment by sasjonge** [comment]
I'm wondering if the current release should not have the headline 2.0.0 but just "Current" or "Changes since last release"

**Comment by mrnolte** [comment]
> @mrnolte I am not so sure about adding it to README.md, maybe better have it in a separate file? I'll have a look at where this is commonly stored

Yeah, my idea was to have the upcoming changes and the latest version in the readme, the rest in a changelog.md file eventually

**Comment by sasjonge** [comment]
Alternativly we could add everything to a changelog file and link to it from the Readme

**Comment by mrnolte** [comment]
Do you prefer this? :)

**Comment by sasjonge** [comment]
Direct link to the README of this PR: https://github.com/mrnolte/soma/tree/release-notes-first-attempt

I think I like it this way. @daniel86 What do you think about having the release notes this way (as a link)?

**Comment by mpomarlan** [comment]
As politicians say, I approve of these release notes.

**Review by daniel86 — APPROVED** [review]

**Pull request merged**
